### PR TITLE
Install Python metadata through pip

### PR DESCRIPTION
**Pull request by diegoferigo**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Requires https://github.com/robotology/idyntree/pull/922 and https://github.com/conda-forge/staged-recipes/pull/16572. cc @traversaro

### CODE REVIEW

**Comment by diegoferigo** [comment]
> > Requires [robotology/idyntree#922](https://github.com/robotology/idyntree/pull/922) and [conda-forge/staged-recipes#16572](https://github.com/conda-forge/staged-recipes/pull/16572). cc @traversaro
> 
> While we wait for those PRs to go through, can you explain the rationale for this change? From what I understand we are mixing Python bindings compiled with `setup.py` and the rest of iDynTree libraries compiled via CMake, with no mechanism in place to make sure that the same CMake options are set to both builds.

Rationale:

- Have a 1:1 match between what is deployed to PyPI and what is distributed through conda-forge.
- The `python.py` file becomes the entrypoint for both PyPI and conda-forge to enable / disable features.
- If needed, the python files can become a subpackage and passing through this new methods would be simpler to maintain.
- The `idyntree` Python package metadata gets included in the `idyntree` conda-forge package, meaning that `pip list` would show that `idyntree` is installed and can be imported.
- If the user installs with `pip` a package from PyPI that has `idyntree` as its dependency, the files already part of the environment but now tracked by pip will get no longer overridden.

**Comment by traversaro** [comment]
Related PR: https://github.com/conda-forge/nlopt-feedstock/pull/37 (even if perhaps not ideal as it just installs an empty METADATA file, not fully compliant to https://packaging.python.org/specifications/recording-installed-packages/ and https://packaging.python.org/specifications/core-metadata/#core-metadata where at least a non-empty `METADATA` with the `Metadata-Version`, `Name` and  `Version` fiels are required).

**Comment by diegoferigo** [comment]
> > The setup.py file becomes the entrypoint for both PyPI and conda-forge to enable / disable features.
> 
> That was the part I was afraid of. To enable/disable features in conda-forge we have the options listed in the `bld.bat`/`build.sh` . I am a bit afraid that if we duplicate those options in yet another place (that my the way is not part of the recipe, so it can easily change without being clear in the version bump PR) this may lead to inconsistencies.

Yep I totally understand the duplication concern, but I want to bring two more points to your attention because this change imo goes in the direction of simplifying rather the duplicating:

- Having a 1:1 feature match between PyPI and conda-forge is fundamental to have Python code (bindings in this way) that provide the same number of features, making all downstream projects compatible regardless of the mean of installation. The simplest way is for conda-forge to pass through setuptools (instead of the other way around). Currently, setup.py contains the default CMake configuration used to package for PyPI, however `diegoferigo/cmake-build-extension` allows to override them from the command line, as done in this PR for `BUILD_SHARED_LIBRARIES`. This means that 1) we start with the same features of PyPI and 2) if we need to modify / add features, we can do it in the `build.*` scripts as it already happens right now. This way, we don't have to mind in most cases to keep aligned the cmake options used for Python because they are already specified in `setup.py`.
- Passing through pip or pypa/build would be in any case necessary in the case where other Python resources that are not generated by CMake are involved. And I'm thinking of a possible future high-level Python wrappers of iDynTree classes, or similar. I think that passing through these tools would make the recipe more generic and consistent.

> > * The idyntree Python package metadata gets included in the idyntree conda-forge package, meaning that pip list would show that idyntree is installed and can be imported.
> > * If the user installs with pip a package from PyPI that has idyntree as its dependency, the files already part of the environment but now tracked by pip will get no longer overridden.
> 
> That seems the interesting feature we are looking for. If I understand well, this can be implemented simply by having something in `${SP_DIR}/idyntree-<version>.dist-info/METADATA` file, where most of that `METADATA` is already in https://github.com/robotology/idyntree/blob/c2010240a1d56fe01e1be5ab20e3b16bcc568856/setup.py#L15 . Do you know if there is a way for generate just the `METADATA` that we need from `setup.py`, without the need to re-compile all the library?

This, with also the other resources you linked in later comments, is another possibility. Though, this would mean adding new logic to the recipe to automatically generate this file, which is already done for us by pip or pypa/build (maybe there's a python function somewhere that takes the setup.cfg and produces the metadata). This being said, although this seems a good option, if I were the maintainer I would prefer going towards this PR, but any solution like the autogeneration of METADATA would work.

---

As discussed f2f, a problem you raised is how to handle the automatic generation of the PyPI version since it's done from the git archive, and the github release tarball does not have git metadata. In this case, I think that a single sed like that writes to `setup.py|cfg` the conda-forge version would suffice as a workaround. Though, again, the automatic generation of METADATA has a similar complexity.

**Comment by diegoferigo** [comment]
If your concern is to keep the CMake options consistent, I just realized that I can update this PR as follows:

1. Revert back to building with CMake the entire project, Python bindings included.
1. Use `setup.py` without any `CMakeExtension` by passing `--no-cmake-extension` option. It would install only the metadata without the need to do it manually, avoiding possible mistakes of operating in low-level.
1. This still needs the workaround to store the right version in `setup.py|cfg`, but it is fairly easy to do.

This seems the best trade off to keep a small complexity.

**Comment by traversaro** [comment]
> 
> 
> @traversaro I managed to fix also the windows builds, if you want to make a more thorough review I think I'm mostly done now. No prob if you want to wait the finalization of the `diffutils` migration before merging.

Great! Yes, thanks, I would prefer for https://github.com/conda-forge/diffutils-feedstock/pull/4 to be merged to verify that CI for aarch64 is working before merging.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
I switched to cross-compilation to workaround https://github.com/conda-forge/status/issues/122 .

**Comment by traversaro** [comment]
Cross-compilation has problems described in https://github.com/conda-forge/conda-smithy/issues/1539 .

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Review by traversaro — APPROVED** [review]

**Pull request merged**
